name: apptainer-test

on:
  pull_request: []

jobs:
  builder:
    name: Test container builds

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.1.2

      - name: Build the container(s)
        run: |
          for definition_file in $(ls *.def); do
            filename_no_suffix=$(basename ${definition_file} .def)
            apptainer build ${filename_no_suffix}.sif ${definition_file}
          done
